[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "simulation-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
evalexpr = "13.1.0"
wasm-bindgen = "0.2"
wee_alloc = { version = "0.4.5", optional = true }

[features]
default = ["wee_alloc"]
